version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - D:\data\mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: clyde_frog
      MONGO_INITDB_ROOT_PASSWORD: EngaMe031EN
    command: ["--auth"]
