services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}" # Клиент
      - "${PORT:-4000}:${PORT:-4000}" # Сервер
    env_file:
      - .env.${NODE_ENV:-development}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:18.4-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    env_file:
      - .env.${NODE_ENV:-development}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
